ClubApp/Controllers/ActiveController.cs
using ClubApp.Models;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClubApp.Controllers
{
    public class ActiveController : Controller
    {
        AppDbContext db = new AppDbContext();

        private AppUserManager _userManager;

        public ActiveController()
        {
        }

        public ActiveController(AppUserManager userManager)
        {
            UserManager = userManager;
        }

        public AppUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<AppUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        // GET: Active
        public ActionResult Index(string cid)
        {
            if (cid != null)
            {
                ClubNumber club = db.ClubNumbers.Find(cid);
                if (club != null)
                {
                    ViewBag.ClubId = cid;
                }
            }
            return View();
        }
        [HttpGet]
        public ActionResult Add(string cid)
        {
            if (cid == null)
            {
                return RedirectToAction("Index");
            }
            ClubNumber club = db.ClubNumbers.Find(cid);
            if (club == null)
            {
                return HttpNotFound("未发现社团" + cid);
            }
            ViewBag.Club = club.Name;
            return View();
        }
        public ActionResult Detail(string aid)
        {
            if (aid == null)
            {
                return RedirectToAction("Index");
            }
            if (!int.TryParse(aid, out int id))
            {
                return HttpNotFound("未发现活动" + aid);
            }
            Activities act = db.Activities.Find(id);
            if (act == null)
            {
                return HttpNotFound("未发现活动" + aid);
            }
            ActDetail model = new ActDetail();
            model.Id = act.Id;
            if (act.Time1 > DateTime.Now)
            {
                model.State = "未开始";
            }
            else if (act.Time2 > DateTime.Now)
            {
                model.State = "进行中";
            }
            else
            {
                model.State = "已结束";
            }
            model.time1 = act.Time1.ToString("yyyy年MM月dd日：HH时mm分ss秒");
            model.time2 = act.Time2.ToString("yyyy年MM月dd日：HH时mm分ss秒");
            if (act.Area == null)
            {
                if (string.IsNullOrEmpty(act.Area0))
                {
                    model.area = "未知";
                }
                else
                {
                    model.area = act.Area0;
                }
            }
            else
            {
                model.area = act.Area.Name;
            }
            model.Title1 = act.Title1;
            model.Title2 = act.Title2;
            model.MaxUser = act.MaxUser == null ? "无限制" : act.MaxUser.ToString()+"人";
            model.Labels = act.Label.Split(',').ToList();
            model.Content = act.Content;
            model.CreateDate = act.CreateDate.ToString("yyyy年MM月dd日：HH时mm分ss秒");
            //统计不同打分的评论个数
            List<Voting> votings = db.Votings.Where(v => v.Active.Id == act.Id).ToList();
            if (votings == null)
            {
                model.Votings = new List<Voting>();
            }
            else
            {
                model.Votings = votings;
            }
            
            int v1=0, v2=0, v3=0, v4=0, v5=0;
            foreach(Voting v in votings)
            {
                if (v.Votes < 1)
                {
                    //小于1分的为无效值
                }
                else if (v.Votes < 2)
                {
                    v1 += 1;
                }
                else if (v.Votes < 3)
                {
                    v2 += 1;
                }
                else if (v.Votes < 4)
                {
                    v3 += 1;
                }
                else if (v.Votes < 5)
                {
                    v4 += 1;
                }
                else if (v.Votes < 6)
                {
                    v5 += 1;
                }
            }
            double av1 = v1 * 1 + v2 * 2 + v3 * 3 + v4 * 4 + v5 * 5;//总分数
            int av2 = v1 + v2 + v3 + v4 + v5;//总评论数
            model.Vote0 =av2==0?0: Math.Round(av1/av2,1);//平均分数，保留一位小数
            model.Vote1 = v1.ToString() + "/" + av2.ToString();
            model.Vote2 = v2.ToString() + "/" + av2.ToString();
            model.Vote3 = v3.ToString() + "/" + av2.ToString();
            model.Vote4 = v4.ToString() + "/" + av2.ToString();
            model.Vote5 = v5.ToString() + "/" + av2.ToString();
            //下述代码为更新活动平均分
            //act.Votes0 = model.Vote0.ToString();
            //db.Entry(act).State = System.Data.Entity.EntityState.Modified;
            //db.SaveChanges();
            return View(model);
        }
        [HttpGet]
        public ActionResult AddAct(string cid)
        {
            if (cid == null)
            {
                return RedirectToAction("Index");
            }
            ClubNumber club = db.ClubNumbers.Find(cid);
            if (club == null)
            {
                Session["Error"] = "未发现社团" + cid;
                return RedirectToAction("Error404", "Home");
            }
            if (club.State!=(int)EnumState.正常)
            {
                Session["Error"] = "活动<" + club.ClubId.ToString() + "-" + club.Name + ">非正常状态，无法发布活动";
                return RedirectToAction("Error404", "Home");
            }
            ActiveListModel model = new ActiveListModel();
            model.ClubID = club.ClubId;
            model.ClubName = club.Name;
            List<Area> areas = db.Areas.Where(a=>a.State==(int)EnumState.正常).ToList();
            model.Areas = new Dictionary<int, string>();
            foreach(Area a in areas)
            {
                model.Areas.Add(a.Id, a.Name);
            }
            return View(model);
        }
        [HttpPost,ValidateInput(false),Authorize]
        public ActionResult AddAct(ActiveListModel model)
        {
            ClubNumber club = db.ClubNumbers.Find(model.ClubID);
            UserNumber u = db.UserNumbers.Find(User.Identity.Name);
            if (club == null)
            {
                Session["Error"] = "未发现社团" + model.ClubID;
                return RedirectToAction("Error404", "Home");
            }
            //保存活动信息
            Activities Act = new Activities()
            {
                Title1 = model.Title1,
                Title2 = model.Title2,
                Content = model.Content,
                MaxUser=model.MaxUser,
                Area0=model.Area0,
                Club = club,
                CreateDate = DateTime.Now,
                User = u,
                State = (int)ActiveState.待提交,
                Votes0="0"
            };
            if (model.Area != null)
            {
                Area a = db.Areas.Find(model.Area);
                if (a != null)
                {
                    Act.Area = a;
                }
            }
            int type;
            int.TryParse(model.Type, out type);
            Act.Type = type;
            if (model.LabelStr?.Length > 1)
            {
                Act.Label = model.LabelStr.Substring(1);
            }
            DateTime t1 ;
            DateTime.TryParse(model.Time1, out t1);
            if (t1 < DateTime.Now)
            {
                ModelState.AddModelError("", "活动开始时间不能小于当前时间");
                return View(model);
            }
            Act.Time1 = t1;
            DateTime.TryParse(model.Time2, out t1);
            Act.Time2 = t1;
            db.Activities.Add(Act);
            db.SaveChanges();
            return View("Index");
        }
        [HttpGet]
        public ActionResult Submit(string aid)
        {
            if (aid == null||(int.TryParse(aid,out int intaid) ==false))
            {
                return RedirectToAction("Manage");
            }
            Activities act = db.Activities.Find(intaid);
            if (act == null)
            {
                Session["Error"] = "未发现活动" + aid;
                return RedirectToAction("Error404", "Home");
            }
            if (act.User.UserId != User.Identity.Name)
            {
                Session["Error"] = "访问被拒绝！编号为" + aid + "的活动非当前登陆用户创建";
                return RedirectToAction("Error404", "Home");
            }
            ActiveSubModel model = new ActiveSubModel()
            {
                Id = act.Id,
                Type = act.Type.ToString(),
                State = Enum.GetName(typeof(ActiveState), act.State),
                Title1 = act.Title1,
                Title2 = act.Title2,
                Content = act.Content,
                Area = act.Area == null ? act.Area0 : act.Area.Name,
                Time1 = act.Time1.ToString(),
                Time2 = act.Time2.ToString(),
                MaxUser = act.MaxUser == null ? "无限制" : act.MaxUser.ToString(),
                Labels = act.Label?.Split(',').ToList()
            };

            return View(model);
        }
        [HttpPost]
        public ActionResult Submit([Bind(Include = "Id,ApplyDesc,ApplyFile")]ActiveSubModel model)
        {
            Activities act = db.Activities.Find(model.Id);
            if (act == null)
            {
                Session["Error"] = "未发现活动" + model.Id;
                return RedirectToAction("Error404", "Home");
            }

ClubApp/Views/Active/Add.cshtml
@model ClubApp.Models.ActiveListModel
@{
    ViewBag.Title = "创建活动";
}

<style>
    .layui-form-danger {
        border-color: red;
    }
</style>
@if ((ViewBag.Res ?? "") == "ApplyOK")
{
    <fieldset class="layui-elem-field">
        <legend>申请结果</legend>
        <div class="layui-field-box text-danger">
            社团申请已成功创建，已为你锁定[@Model.Id]的账号，请在24小时内通过菜单：[社团-@Html.ActionLink("管理我的社团", "MyClubs", "Clubs")] 上传申请材料进行提交本次申请，逾期分配的账号将被收回。
        </div>
    </fieldset>
}
<fieldset class="layui-elem-field layui-field-title">
    <legend>@ViewBag.Club 创建活动</legend>
</fieldset>
@using (Html.BeginForm("Add", "Active", FormMethod.Post, new { @class = "layui-form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="layui-form-item">
        @Html.LabelFor(m => m.Labels, new { @class = "layui-form-label" })
        <div class="layui-input-block">
            <input type="checkbox" name="like[write]" title="写作">
            <input type="checkbox" name="like[read]" title="阅读">
            <input type="checkbox" name="like[game]" title="游戏">
            <input type="checkbox" name="like[write]" title="写作">
            <input type="checkbox" name="like[read]" title="阅读">
            <input type="checkbox" name="like[game]" title="游戏">
            <input type="checkbox" name="like[write]" title="写作">
            <input type="checkbox" name="like[read]" title="阅读">
            <input type="checkbox" name="like[game]" title="游戏">
            <input type="checkbox" name="like[write]" title="写作">
            <input type="checkbox" name="like[read]" title="阅读">
            <input type="checkbox" name="like[game]" title="游戏">
            <input type="checkbox" name="like[write]" title="写作">
            <input type="checkbox" name="like[read]" title="阅读">
            <input type="checkbox" name="like[game]" title="游戏">
            <input type="button" class="layui-btn layui-btn-sm layui-btn-primary" onclick="addlabel()" value="更多" />
        </div>
    </div>
    <div class="layui-form-item">
        @Html.LabelFor(m => m.Title1, new { @class = "layui-form-label" })
        <div class="layui-input-block">
            @Html.TextBoxFor(m => m.Title1, new { @class = "layui-input", autocomplete = "off" })
        </div>
    </div>

    <div class="layui-form-item">
        @Html.LabelFor(m => m.Title2, new { @class = "layui-form-label" })
        <div class="layui-input-block">
            @Html.TextBoxFor(m => m.Title2, new { @class = "layui-input", autocomplete = "off" })
        </div>
    </div>
    <div class="layui-form-item">
        @Html.LabelFor(m => m.MaxUser, new { @class = "layui-form-label" })
        <div class="layui-input-inline">
            @Html.TextBoxFor(m => m.MaxUser, new { @class = "layui-input", autocomplete = "off" })
        </div>
        <div class="layui-form-mid layui-word-aux">会产生对应的门票数，若不输入则无限制</div>
    </div>
    <div class="layui-form-item">
        <div class="layui-inline">
            @Html.LabelFor(m => m.Area, new { @class = "layui-form-label" })
            <div class="layui-input-block">
                <select name="interest" lay-filter="aihao">
                    <option value=""></option>
                    <option value="0">写作</option>
                    <option value="1" selected="">阅读</option>
                    <option value="2">游戏</option>
                    <option value="3">音乐</option>
                    <option value="4">旅行</option>
                </select>
            </div>
        </div>
        <div class="layui-inline">
            <div class="layui-input-inline">
                <input type="button" class="layui-btn layui-btn-primary layui-btn-sm" value="点击查看" />
            </div>
            <label class="layui-form-mid layui-word-aux">请查看该地点的预约信息以防止与其他活动冲突</label>
        </div>
    </div>
    <div class="layui-form-item">
        <div class="layui-inline">
            @Html.LabelFor(m => m.Time1, new { @class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.TextBoxFor(m => m.Time1, new { @class = "layui-input", @readonly = "true" })
            </div>
        </div>
        <div class="layui-inline">
            @Html.LabelFor(m => m.Time2, new { @class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.TextBoxFor(m => m.Time2, new { @class = "layui-input", @readonly = "true" })
            </div>
        </div>
        <div class="layui-inline">
            <input type="button" class="layui-btn" value="点击选择时间" alt="活动预约时间只能为一天后的30天内" id="opendateselect" />
            <div class="layui-input-block layui-hide">
                <input type="text" class="layui-input" id="test10" placeholder=" - ">
            </div>
        </div>
    </div>
    <div class="layui-form-item">
        @Html.LabelFor(m => m.Content, new { @class = "layui-form-label" })
        <div class="layui-input-block">
            <textarea name="Content" required lay-verify="required|maxlength" placeholder="请简述活动内容（最大500字符）" class="layui-textarea"></textarea>
        </div>
    </div>
    <textarea id="demo" style="display: none;"></textarea>
    <div class="layui-form-item">
        <div class="layui-input-block">
            <input type="submit" class="layui-btn" lay-submit value="确认提交" />
            <button type="reset" class="layui-btn layui-btn-primary">重置</button>
        </div>
    </div>

}

<script>
    //Demo
    layui.use(['form', 'laydate','layedit'], function () {
        var form = layui.form,
            laydate = layui.laydate,
            layedit = layui.layedit;
        form.verify({
            maxlength: function (value, item) {
                if (value.length > 500) {
                    return '超过最大长度[500]个字符！'
                }
            }
        })
        //日期时间范围
        laydate.render({
            elem: '#test10'
            , type: 'datetime'
            , zIndex: 10000
            , range: true
            , calendar: true
            , eventElem: '#opendateselect'
            , trigger: 'click'
            , min: 1 //1天后
            , max: 30 //7天后
            , done: function (value, date, endDate) {
                if (date.year) {
                    $("#Time1").val(date.year + "年" + date.month + "月" + date.date + "日" + date.hours + "时" + date.minutes + "分" + date.seconds + "秒");
                    $("#Time2").val(endDate.year + "年" + endDate.month + "月" + endDate.date + "日" + endDate.hours + "时" + endDate.minutes + "分" + endDate.seconds + "秒");
                }
                else {
                    $("#Time1").val("")
                    $("#Time2").val("")
                }
            }
        });
        layedit.build('demo'); //建立编辑器
    });
    function addlabel() {
        layer.msg('暂不支持自定义标签');
    }
</script>

ClubApp/Views/Active/AddAct.cshtml
@model ClubApp.Models.ActiveListModel
@{
    ViewBag.Title = "AddAct";
}

<fieldset class="layui-elem-field layui-field-title">
    <legend>@Model.ClubName | 填写活动信息</legend>
</fieldset>
@using (Html.BeginForm("AddAct", "Active", FormMethod.Post, new { @class = "layui-form layui-form-pane" }))
{
    <div class="layui-form-item layui-row layui-col-space8">
        <div class="layui-col-sm4">
            <label class="layui-form-label">活动类型</label>
            <div class="layui-input-block">
                <select name="Type" lay-verify="required" lay-filter="aihao">
                    <option value=""></option>
                    <option value="1">私人</option>
                    <option value="2" selected="">社团</option>
                    <option value="3">社联</option>
                    <option value="4">院级</option>
                    <option value="5">校级</option>
                    <option value="6">校级官方</option>
                    <option value="7">校外</option>
                    <option value="0">其他</option>
                </select>
            </div>
        </div>
        <div class="layui-col-sm8">
            @Html.LabelFor(m => m.Title1, new { @class = "layui-form-label" })
            <div class="layui-input-block">
                <input type="text" name="Title1" id="Title1" lay-verify="required" class="layui-input" , autocomplete="off" />
            </div>
        </div>
    </div>
    <div class="layui-form-item">
        @Html.LabelFor(m => m.Title2, new { @class = "layui-form-label" })
        <div class="layui-input-block">
            <input type="text" name="Title2" id="Title2" lay-verify="required" class="layui-input" autocomplete="off" placeholder="副标题/简介：50字以内" />
        </div>
    </div>
    <div class="layui-form-item layui-form-text">
        <textarea placeholder="请输入内容" id="Content" name="Content" class="layui-textarea"></textarea>
    </div>
    <div class="layui-form-item">
        @Html.LabelFor(m => m.Area, new { @class = "layui-form-label" })
        <div class="layui-input-inline">
            <select name="Area" lay-verify="required" lay-filter="aihao">
                @foreach (var item in Model.Areas)
                {
                    <option value="@item.Key">@item.Value</option>
                }
            </select>
        </div>
        <div class="layui-form-mid layui-word-aux">
            请查看该地点的预约信息以防止与其他活动冲突
            <a href="#" style="color:red">（点击查看）</a>
        </div>
    </div>
    <div class="layui-form-item">
        <label class = "layui-form-label">地点备注</label>
        <div class="layui-input-block">
            @Html.TextBoxFor(m => m.Area0, new { @class = "layui-input",placeholder="备注或其他地点信息" })
        </div>
    </div>
    <div class="layui-form-item">
        @Html.LabelFor(m => m.MaxUser, new { @class = "layui-form-label" })
        <div class="layui-input-inline">
            @Html.TextBoxFor(m => m.MaxUser, new { @class = "layui-input" })
        </div>
        <div class="layui-form-mid layui-word-aux">
            若无人数限制请不要填写此项
        </div>
    </div>
    <div class="layui-form-item">
        <div class="layui-inline">
            @Html.LabelFor(m => m.Time1, new { @class = "layui-form-label" })
            <div class="layui-input-block">
                <input type="text" name="Time1" id="Time1" lay-verify="required" class="layui-input" readonly>
            </div>
        </div>
        <div class="layui-inline">
            @Html.LabelFor(m => m.Time2, new { @class = "layui-form-label" })
            <div class="layui-input-block">
                <input type="text" name="Time2" id="Time2" lay-verify="required" class="layui-input" readonly>
            </div>
        </div>
        <div class="layui-inline">
            <input type="button" class="layui-btn" value="点击选择时间" alt="活动预约时间只能为一天后的30天内" id="opendateselect" />
            <div class="layui-input-block layui-hide">
                <input type="text" class="layui-input" id="test10" placeholder=" - ">
            </div>
        </div>
    </div>
    <div class="layui-form-item">
        @Html.LabelFor(m => m.LabelStr, new { @class = "layui-form-label" })
        <div class="layui-input-block">
            <input type="checkbox" name="label" title="文学">
            <input type="checkbox" name="label" title="编程">
            <input type="checkbox" name="label" title="游戏">
            <input type="checkbox" name="label" title="体育">
            <input type="checkbox" name="label" title="社交">
            <input type="checkbox" name="label" title="音乐">
            <input type="checkbox" name="label" title="科学">
            <input type="checkbox" name="label" title="商务">
            <input type="checkbox" name="label" title="男女">
            <input type="button" class="layui-btn layui-btn-sm layui-btn-primary" onclick="addlabel()" value="更多" />
            @Html.TextBoxFor(m => m.LabelStr, new { @class = "layui-input layui-hide" })
        </div>
    </div>
    <div class="layui-form-item">
        <button class="layui-btn" lay-submit lay-filter="demo2">提交创建</button>
        <button type="button" class="layui-btn" onclick="getcontent()"><i class="layui-icon layui-icon-play"></i>预览</button>
        <input type="button" class="layui-btn" onclick="gettext()" value="获取纯文本" />
        @Html.TextBoxFor(m => m.ClubID, new { @class = "layui-input layui-hide" })
    </div>
}
<script>
//Demo
var index;
var getcontent;
var gettext;
layui.use(['form', 'laydate', 'layedit'], function () {
    var form = layui.form,
        laydate = layui.laydate,
        layedit = layui.layedit;

      //监听提交
    form.on('submit(demo2)', function (data) {
        if (layedit.getContent(index).length < 1) {
            layer.msg("活动内容不能为空");
            return false;
        }
        if ($('input[name="label"]:checked').length > 3) {
            layer.msg("标签最多选择3个");
            return false;
        }
        var label="";
        $('input[name="label"]:checked').each(function () {
             label= label + "," + this.title;
        });
        $("#LabelStr").val(label);
    });

    layedit.set({
      uploadImage: {
        url: '/Upload/UploadActImg?cid='+@Model.ClubID,
      }
    });
    index = layedit.build('Content'); //建立编辑器

    getcontent = function () {
        layer.open({
            type: 1 //此处以iframe举例
                    ,title: '预览'
                    ,area: ['50%', '100%'],
            offset:'r'
                    ,shade: 0
                    ,maxmin: true
                    ,content: layedit.getContent(index)

        });
    }
    gettext = function () {
        alert(layedit.getText(index))
    }
    //日期时间范围
        laydate.render({
            elem: '#test10'
            , type: 'datetime'
            , zIndex: 10000
            , range: true
            , calendar: true
            , eventElem: '#opendateselect'
            , trigger: 'click'
            , min: 1 //1天后
            , max: 30 //7天后
            , done: function (value, date, endDate) {
                if (date.year) {
                    $("#Time1").val(date.year + "-" + date.month + "-" + date.date + " " + date.hours + ":" + date.minutes + ":" + date.seconds);
                    $("#Time2").val(endDate.year + "-" + endDate.month + "-" + endDate.date + " " + endDate.hours + ":" + endDate.minutes + ":" + endDate.seconds);
                }
                else {
                    $("#Time1").val("")
                    $("#Time2").val("")
                }
            }
        });
});
function addlabel() {
    layer.msg('暂不支持自定义标签');
}

</script>

ClubApp/Views/Active/Ticket.cshtml
@model IEnumerable<ClubApp.Models.UserTicketView>
@{
    ViewBag.Title = "活动门票";
}
<style>
    .title span {
        border: 1px solid darkgrey;
        padding: 10px;
        border-radius: 10px;
        box-shadow: 0 0 10px grey;
        margin:0 4px;
    }
    .title span i {
        color: white;
        font-weight: bold;
    }
    .title button {
        line-height: 100%;
        background-color: lightpink;
        color: white;
        font-weight: bold;
    }
</style>
<h2>活动门票:@ViewBag.Act</h2>

<fieldset class="layui-elem-field layui-field-title" style="margin-top: 30px;">
    <legend class="title">
        <span style="background-color: yellowgreen;">总投放门票数 <i>@ViewBag.Count0</i></span>
        <span style="background-color: coral;">已被领取 <i>@ViewBag.Count1</i></span>
        <span style="background-color: dodgerblue;">剩余 <i>@ViewBag.Count2</i></span>
        @if(ViewBag.Count2>0)
        {
        <button class="layui-btn layui-btn-sm layui-btn-primary" type="button" onclick="getticket()"><i class="layui-icon layui-icon-senior"></i>点击获取门票</button>
        }
        else
        {
        <button class="layui-btn layui-btn-sm layui-btn-primary" type="button" onclick="noticket()"><i class="layui-icon layui-icon-senior"></i>门票告罄</button>
        }
    </legend>
</fieldset>
<ul class="layui-timeline">
    <li class="layui-timeline-item">
        <i class="layui-icon layui-timeline-axis"></i>
        <div class="layui-timeline-content layui-text">
            <div class="layui-timeline-title">@(DateTime.Now.ToString("yyyy年MM月dd日-HH时mm分ss秒")) 剩余门票 @ViewBag.Count2</div>
        </div>
    </li>
    @foreach (var item in Model)
    {
        <li class="layui-timeline-item">
            <i class="layui-icon layui-timeline-axis"></i>
            <div class="layui-timeline-content layui-text">
                <div class="layui-timeline-title">@item.CreateDate，@item.User 获取门票 ——@item.Desc </div>
            </div>
        </li>
    }
    <li class="layui-timeline-item">
        <i class="layui-icon layui-anim layui-anim-rotate layui-anim-loop layui-timeline-axis"></i>
        <div class="layui-timeline-content layui-text">
            <div class="layui-timeline-title">本次活动投放 @ViewBag.Count0 张门票</div>
        </div>
    </li>
</ul>

<script>
    layui.use(['layer'], function () {

    })
    function getticket() {
        layer.load();
        setTimeout(gotticket,2000)
    }
    function gotticket() {
        $.post("/Active/GetTicket", { "aid": @ViewBag.ActId }, function (data) {
            if (data == "OK") {
                layer.closeAll('loading');
                layer.msg("成功获取到门票！");
                setTimeout("location.reload()", 2000);
            }
            else {
                layer.closeAll('loading');
                layer.msg(data, {icon:2,time:6000});
            }
        })
    }
    function noticket() {
        layer.msg("抱歉，门票已告罄！", { icon: 2 });
    }
    $("#e2").addClass("layui-this");
    $("#e2").parents("li").addClass("layui-nav-itemed")
</script>