ClubApp/Controllers/BAdminController.cs
using ClubApp.Models;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ClubApp.Controllers
{
    [Authorize]
    public class BAdminController : Controller
    {
        AppDbContext db = new AppDbContext();
        // GET: BAdmin
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Notice()
        {
            return View();
        }
        [HttpGet]
        public ActionResult AddNotice()
        {
            return View();
        }
        [HttpPost,ValidateInput(false)]
        public ActionResult AddNotice(NoticeView model)
        {
            UserNumber tuser = db.UserNumbers.Find(User.Identity.Name);
            Notice nn = new Notice();
            nn.Content = model.Content;
            nn.Title1 = model.Title1;
            nn.Title2 = model.Title2;
            nn.type = model.type;
            nn.User = tuser;
            nn.CreateDate = DateTime.Now;
            db.Notices.Add(nn);
            db.SaveChanges();
            return RedirectToAction("Notice");
        }
        public ActionResult NoticesA(int? nid)
        {
            if (nid == null)
            {
                return RedirectToAction("Notice");
            }
            Notice model = db.Notices.Find(nid);
            if (model == null)
            {
                Session["Msg"] = "未发现公告"+nid.ToString();
                RedirectToAction("Erroe404", "Home");
            }
            return View(model);
        }

        public ActionResult AuditClub(string Msg = "", int s = 0)
        {
            if (!string.IsNullOrEmpty(Msg))
            {
                ViewBag.Msg = Msg;
            }
            List<ApplyAudit> models = new List<ApplyAudit>();
            int st = (int)s;
            if (s > 0 && s < 4)
            {
                models = db.ApplyAudits.Where(a => a.Type.Id == (int)SQType.注册社团 && a.CheckState == st).OrderBy(a => a.Id).ToList();
            }
            else
            {
                models = db.ApplyAudits.Where(a => a.Type.Id == (int)SQType.注册社团).OrderBy(a => a.Id).ToList();
            }

            return View(models);
        }
        public ActionResult AuditClubA(int? id)
        {
            if (id == null)
            {
                Session["Error"] = "未找到指定的社团申请";
                return RedirectToAction("Error404", "Home");
            }
            ApplyAudit AppA = db.ApplyAudits.Find(id);
            if (AppA == null)
            {
                Session["Error"] = "未找到指定的社团申请" + id;
                return RedirectToAction("Error404", "Home");
            }
            ClubNumber club = AppA.Club;
            if (club == null)
            {
                Session["Error"] = "未从申请任务[" + id + "]中发现社团信息";
                return RedirectToAction("Error404", "Home");
            }
            ApplyClubSubModel model = new ApplyClubSubModel()
            {
                ClubId = club.ClubId,
                Type = club.Type.Name,
                Name = club.Name,
                HeadImg = club.HeadImg,
                ShortDesc = club.ShortDesc,
                Desc = club.Desc,
                State = Enum.GetName(typeof(EnumState), club.State),
                CreateDate = club.CreateDate == null ? "未知" : club.CreateDate.ToString(),
                User = club.User.UserName,
                ApplyDesc = AppA.ApplicationDesc,
                ApplyFile = AppA.ApplicationFiled,
                AuditDate = AppA.AuditDate == null ? "未知" : AppA.AuditDate.ToString(),
                AuditTime = AppA.AuditTimes ?? 0,
                AuditId = AppA.Id
            };
            return View(model);
        }
        public ActionResult AuditClubDetail(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("AuditClub");
            }
            List<AuditDetail> audits = db.AuditDetails.Where(a => a.ApplyId == id).OrderBy(a => a.Id).ToList();

            return View(audits);
        }
        public ActionResult AuditClubB()
        {
            return View();
        }
        public async Task<ActionResult> AuditClubAY(int? id, string AuditDesc = "")
        {
            if (id == null)
            {
                Session["Error"] = "错误操作！审批过程未发现任务编号";
                return RedirectToAction("Error404", "Home");
            }
            ClubNumber club = db.ClubNumbers.Where(c => c.AuditID == id).FirstOrDefault();
            if (club == null)
            {
                Session["Error"] = "未发现社团";
                return RedirectToAction("Error404", "Home");
            }
            int res = AuditFun(id ?? 0, EnumAuditState.通过, AuditDesc);
            if (res == 1)
            {
                return RedirectToAction("AuditClub", new { Msg = "社团申请任务[" + id + "]审批成功" });
            }
            else if (res == 2) 
            {
                club.State = (int)EnumState.正常;
                club.CreateDate2 = DateTime.Now;
                db.Entry(club).State = System.Data.Entity.EntityState.Modified;
                if (club.User != null)
                {
                    AppUser uid = db.Users.Where(u => u.UserName == club.User.UserId).FirstOrDefault();
                    AppUserManager userManager= HttpContext.GetOwinContext().GetUserManager<AppUserManager>();
                    bool c= userManager.IsInRoleAsync(uid.Id, "CAdmin").Result;
                    if (!c)
                    {
                        await userManager.AddToRoleAsync(uid.Id, "CAdmin");
                    }
                }
                db.SaveChanges();
                return RedirectToAction("AuditClub", new { Msg = "社团申请任务[" + id + "]审批成功" });
            }
            else
            {
                return RedirectToAction("AuditClub", new { Msg = "失败！社团申请任务[" + id + "]审批失败" });
            }
        }
        public ActionResult AuditClubAN(int? id, string AuditDesc)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClubNumber club = db.ClubNumbers.Where(c => c.AuditID == id).FirstOrDefault();
            if (club == null)
            {
                Session["Error"] = "未发现社团";
                return RedirectToAction("Error404", "Home");
            }
            int res = AuditFun(id ?? 0, EnumAuditState.拒绝, AuditDesc);
            if (res==1)
            {
                club.State = (int)EnumState.已失效;
                db.Entry(club).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("AuditClub", new { Msg = "社团申请任务[" + id + "]拒绝成功" }); ;
            }
            else
            {
                return RedirectToAction("AuditClub", new { Msg = "失败！社团申请任务[" + id + "]拒绝失败" });
            }
        }
        public int AuditFun(int id, EnumAuditState state, string AuditDesc = "")
        {
            ApplyAudit AppA = db.ApplyAudits.Find(id);
            if (AppA == null)
            {
                return 0;
            }
            else if (AppA.CheckState != (int)EnumAuditState.创建)
            {
                return 0;
            }
            //ClubNumber club = AppA.Club;
            if (AppA.Type == null)
            {
                return 0;
            }
            AuditDetail audit = new AuditDetail()
            {
                ApplyId = AppA.Id,
                CheckState = (int)state,
                AuditUser = db.UserNumbers.Find(User.Identity.Name),
                AuditDesc = AuditDesc,
                AuditDate = DateTime.Now
            };
            //AuditDetail audit1 = db.AuditDetails.Where(a => a.ApplyId == AppA.Id).OrderByDescending(a => a.AuditDate).FirstOrDefault();
            //if (audit1 != null)
            //{
            //    audit.FromUser = audit1.AuditUser;
            //}
            if (state == EnumAuditState.通过)
            {
                AppA.AuditTimes += 1;
                AppA.AuditDate = DateTime.Now;
                if (AppA.AuditTimes > 2)
                {
                    AppA.CheckState = (int)state;
                }
                db.Entry(AppA).State = System.Data.Entity.EntityState.Modified;
                db.AuditDetails.Add(audit);
                db.SaveChanges();
                if (AppA.AuditTimes > 2)
                {
                    return 2;
                }
                return 1;
            }
            else if (state == EnumAuditState.拒绝)
            {
                AppA.AuditTimes += 1;

                AppA.CheckState = (int)state;
                AppA.AuditDate = DateTime.Now;
                db.Entry(AppA).State = System.Data.Entity.EntityState.Modified;
                db.AuditDetails.Add(audit);
                db.SaveChanges();
                return 1;
            }
            else
            {
                return 0;
            }

        }
        public ActionResult AuditAct(string Msg = "", int s = 0) 
        {
            if (!string.IsNullOrEmpty(Msg))
            {
                ViewBag.Msg = Msg;
            }
            return View();
        }
        public ActionResult AuditActA(string id)
        {
            if (id == null || (int.TryParse(id, out int intaid) == false))
            {
                return RedirectToAction("Manage");
            }
            Activities act = db.Activities.Where(a => a.AuditID == intaid).FirstOrDefault();
            if (act == null)
            {
                Session["Error"] = "未发现活动" + id;

ClubApp/Views/BAdmin/AddNotice.cshtml
@model ClubApp.Models.NoticeView
@{
    ViewBag.Title = "发布公告";
}
<fieldset class="layui-elem-field layui-field-title">
    <legend>发布公告</legend>
</fieldset>
@using (Html.BeginForm("AddNotice", "BAdmin", FormMethod.Post, new { @class = "layui-form layui-form-pane" }))
{
    <div class="layui-form-item layui-row layui-col-space8">
        <div class="layui-col-sm4">
            <label class="layui-form-label">公告类型</label>
            <div class="layui-input-block">
                <select name="Type" lay-verify="required" lay-filter="aihao">
                    <option value=""></option>
                    <option value="1">私人</option>
                    <option value="2" selected="">社团</option>
                    <option value="3">社联</option>
                    <option value="4">院级</option>
                    <option value="5">校级</option>
                    <option value="6">校级官方</option>
                    <option value="7">校外</option>
                    <option value="0">其他</option>
                </select>
            </div>
        </div>
        <div class="layui-col-sm8">
            @Html.LabelFor(m => m.Title1, new { @class = "layui-form-label" })
            <div class="layui-input-block">
                <input type="text" name="Title1" id="Title1" lay-verify="required" class="layui-input" , autocomplete="off" />
            </div>
        </div> 
    </div>
    <div class="layui-form-item">
        @Html.LabelFor(m => m.Title2, new { @class = "layui-form-label" })
        <div class="layui-input-block">
            <input type="text" name="Title2" id="Title2" lay-verify="required" class="layui-input" autocomplete="off" placeholder="副标题/简介：50字以内" />
        </div>
    </div>
    <div class="layui-form-item layui-form-text">
        <textarea placeholder="请输入内容" id="Content" name="Content" class="layui-textarea"></textarea>
    </div>
    <div class="layui-form-item">
        <button class="layui-btn" lay-submit lay-filter="demo2">提交发布</button>
        <button type="button" class="layui-btn" onclick="getcontent()"><i class="layui-icon layui-icon-play"></i>预览</button>
    </div>
}
<script>
//Demo
var getcontent;
layui.use(['form', 'layedit'], function () {
    var form = layui.form,
        layedit = layui.layedit;

      //监听提交
    form.on('submit(demo2)', function (data) {
        if (layedit.getContent(index).length < 1) {
            layer.msg("活动内容不能为空");
            return false;
        }
    });

    layedit.set({
      uploadImage: {
        url: '/Upload/UploadImg?t=notic',
      }
    });
    index = layedit.build('Content'); //建立编辑器

    getcontent = function () {
        layer.open({
            type: 1 //此处以iframe举例
                    ,title: '预览'
                    ,area: ['50%', '100%'],
            offset:'r'
                    ,shade: 0
                    ,maxmin: true
                    ,content: layedit.getContent(index)

        });
    }
});

</script>

ClubApp/Views/BAdmin/AuditAct.cshtml
@{
    ViewBag.Title = "活动审批";
}

<h2>@ViewBag.Msg</h2>
<fieldset class="layui-elem-field layui-field-title">
    <legend>活动审批</legend>
</fieldset>
<table id="demo" lay-filter="test"></table>
<script type="text/html" id="applystate">
    {{#  if (d.CheckState ==="通过"){ }}
    <span style="color:green;">{{d.CheckState}}</span>
    {{# } else if (d.CheckState ==="拒绝"){ }}
    <span style="color:red;">{{d.CheckState}}</span>
    {{# } else{ }}
    <span>{{d.CheckState}}</span>
    {{# } }}
</script>
<script type="text/html" id="barDemo">
    <!-- 这里同样支持 laytpl 语法，如： -->
    <a class="layui-btn layui-btn-primary layui-btn-xs" href="/BAdmin/AuditClubDetail?id={{d.Id}}">查看记录</a>
    {{#  if(d.CheckState ==="创建"){ }}
    <a class="layui-btn layui-btn-xs" href="/BAdmin/AuditActA?id={{d.Id}}">审批</a>
    {{# } }}
</script>
<script>
layui.use('table', function(){
  var table = layui.table;

  //第一个实例
  table.render({
    elem: '#demo'
    ,height: 400
    ,url: '/GetData/GetApplyData' //数据接口
    ,page: true //开启分页
    ,cols: [[ //表头
      { field: 'Id', title: '申请编号',  sort: true}
      , { field: 'Club', title: '申请社团',  sort: true }
      , { field: 'ApplyUser', title: '申请人', sort: true}
      , { field: 'ApplyDate', title: '申请日期', sort: true}
        , { field: 'AuditDate', title: '处理日期', sort: true }
        , { field: 'AuditTimes', title: '审批次数', sort: true }
      , { field: 'CheckState', title: '审批进度', sort: true , templet: '#applystate'}
      , { fixed: 'right', title: '操作', align:'center', toolbar: '#barDemo'} //这里的toolbar值是模板元素的选择器
    ]]
  });

      //监听行工具事件
  table.on('tool(test)', function(obj){ //注：tool 是工具条事件名，test 是 table 原始容器的属性 lay-filter="对应的值"
    var data = obj.data //获得当前行数据
    ,layEvent = obj.event; //获得 lay-event 对应的值
    if(layEvent === 'outclub'){
      layer.msg('社长舍不得你，请原地写30000字退社申请，否则暂不允许你退社');
    }
  });

});
    $("#b2").addClass("layui-this");
    $("#b2").parents("li").addClass("layui-nav-itemed")
</script>

ClubApp/Views/BAdmin/AuditActA.cshtml
@model ClubApp.Models.ActiveSubModel
@{
    ViewBag.Title = "提交活动申请";
}
<style>
    .form-diy-r {
        padding: 9px 15px;
        display: block;
    }

    .layui-form-text {
        border: 1px solid #e6e6e6;
        border-radius: 2px;
        padding: 15px 0;
    }

    .layui-checkbox-disbaled span {
        background-color: #5FB878 !important;
    }
</style>
<fieldset class="layui-elem-field layui-field-title">
    <legend>@Model.ClubName | 提交活动申请</legend>
</fieldset>
<div class="layui-form">
    <div class="layui-form-item layui-row layui-col-space8">
        <div class="layui-col-sm4">
            @Html.LabelFor(m => m.Type, new { @class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.TextBoxFor(m => m.Type, new { @class = "layui-input", @readonly = true })
            </div>
        </div>
        <div class="layui-col-sm8">
            @Html.LabelFor(m => m.Title1, new { @class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.TextBoxFor(m => m.Title1, new { @class = "layui-input", @readonly = true })
            </div>
        </div>
    </div>
    <div class="layui-form-item">
        @Html.LabelFor(m => m.Title2, new { @class = "layui-form-label" })
        <div class="layui-input-block">
            @Html.TextBoxFor(m => m.Title2, new { @class = "layui-input", @readonly = true })
        </div>
    </div>
    <div class="layui-form-item layui-form-text">
        @(new HtmlString(Model.Content))
    </div>
    <div class="layui-form-item">
        @Html.LabelFor(m => m.Area, new { @class = "layui-form-label" })
        <div class="layui-input-inline">
            @Html.TextBoxFor(m => m.Area, new { @class = "layui-input", @readonly = true })
        </div>
        <div class="layui-form-mid layui-word-aux">
            请查看该地点的预约信息以防止与其他活动冲突
            <a href="#" style="color:red">（点击查看）</a>
        </div>
    </div>
    <div class="layui-form-item">
        @Html.LabelFor(m => m.MaxUser, new { @class = "layui-form-label" })
        <div class="layui-input-inline">
            @Html.TextBoxFor(m => m.MaxUser, new { @class = "layui-input", @readonly = true })
        </div>
        <div class="layui-form-mid layui-word-aux">
            若无人数限制请不要填写此项
        </div>
    </div>
    <div class="layui-form-item">
        <div class="layui-inline">
            @Html.LabelFor(m => m.Time1, new { @class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.TextBoxFor(m => m.Time1, new { @class = "layui-input", @readonly = true })
            </div>
        </div>
        <div class="layui-inline">
            @Html.LabelFor(m => m.Time2, new { @class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.TextBoxFor(m => m.Time2, new { @class = "layui-input", @readonly = true })
            </div>
        </div>
        <div class="layui-inline">
            <input type="button" class="layui-btn layui-btn-disabled" value="点击选择时间" alt="活动预约时间只能为一天后的30天内" id="opendateselect" />
        </div>
    </div>
    <div class="layui-form-item">
        @Html.LabelFor(m => m.Labels, new { @class = "layui-form-label" })
        <div class="layui-input-block">
            @if (Model.Labels != null)
            {
                foreach (string lab in Model.Labels)
                {
                    <input type="checkbox" name="label" checked disabled value="@lab" title="@lab">
                }
            }
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">申请理由</label>
        <div class="layui-input-block">
            <textarea name="ApplyDesc" readonly placeholder="请简述你创建活动的原因及意义（最大500字符）" class="layui-textarea">@(Model.ApplyDesc?? "")</textarea>
        </div>
    </div>
    <div class="layui-form-item">
        @Html.LabelFor(m => m.ApplyFile, new { @class = "layui-form-label" })
        <div class="layui-input-block">
            @if (string.IsNullOrEmpty(Model.ApplyFile))
            {
                <label class="form-diy-r">该用户未上传相关审核文件，建议拒绝该申请</label>
            }
            else
            {
                <a href="~/@Model.ApplyFile" class="form-diy-r" style="color:#009688;">请点击下载查看</a>
            }
        </div>
    </div>
    <div class="layui-form-item">
        <div class="layui-input-block">
            @if (Model.State != "待审批")
            {
                <label class="form-diy-r layui-bg-red">该申请任务状态为非允许审批：@Model.State</label>
            }
            else
            {
                <fieldset class="layui-elem-field">
                    <legend>审批</legend>
                    <div class="layui-field-box">
                        <div class="layui-form-item">
                            @Html.LabelFor(m => m.AuditTime, new { @class = "layui-form-label" })
                            <div class="layui-input-inline">
                                @Html.TextBoxFor(m => m.AuditTime, new { @class = "layui-input", @readonly = "true" })
                            </div>
                            <div class="layui-form-mid layui-word-aux">
                                原则上需要不同的管理员总计审批三次以上才能最后通过。
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <input type="button" class="layui-btn" value="通过" onclick="subpass(@Model.AuditId)" />
                            <input type="button" class="layui-btn layui-btn-danger" value="拒绝" onclick="subnopass(@Model.AuditId)" />
                            <input type="button" class="layui-btn layui-btn-primary" value="返回" onclick="JavaScript:history.back(-1)" />
                        </div>
                    </div>
                </fieldset>
            }
        </div>
    </div>
</div>
    <script>
        //Demo
    layui.use('form', function () {
        var form = layui.form;   
    });
    function subpass(aid) {
    layer.open({
        type: 1,
        title:'填写审批备注',
        skin: 'layui-layer-rim', //加上边框
      area: ['420px', '240px'], //宽高
      content: '<form class="layui-form" action="/BAdmin/AuditActAY" method="post"><input name="id" type="hidden" value="'+aid+'" /><div class="layui-form-item"><label class="layui-form-label">审批备注</label><div class="layui-input-block"><textarea name="AuditDesc" placeholder="请简述本次审批备注（最大500字符）" class="layui-textarea"></textarea></div></div><div class="layui-form-item"><div class="layui-input-block"><input type="submit" class="layui-btn" value="确认" /><input type="button" class="layui-btn layui-btn-primary" value="取消" onclick="closelay()" /></div></div></form>'
    });
    }
    function subnopass(aid) {
    layer.open({
        type: 1,
        title:'填写审批备注',
        skin: 'layui-layer-rim', //加上边框
      area: ['420px', '240px'], //宽高
      content: '<form class="layui-form" action="/BAdmin/AuditActAN" method="post"><input name="id" type="hidden" value="'+aid+'" /><div class="layui-form-item"><label class="layui-form-label">审批备注</label><div class="layui-input-block"><textarea name="AuditDesc" placeholder="请简述本次审批备注（最大500字符）" class="layui-textarea"></textarea></div></div><div class="layui-form-item"><div class="layui-input-block"><input type="submit" class="layui-btn" value="确认" /><input type="button" class="layui-btn layui-btn-primary" value="取消" onclick="closelay()" /></div></div></form>'
    });
    }
    function closelay() {
        layer.closeAll();
    }
    </script>

ClubApp/Views/BAdmin/AuditClub.cshtml
@model IEnumerable<ClubApp.Models.ApplyAudit>
@{
    ViewBag.Title = "社团审批";
}

<h2>@ViewBag.Msg</h2>
<fieldset class="layui-elem-field layui-field-title">
    <legend>社团审批</legend>
</fieldset>
<div class="layui-form">
    <table class="layui-table">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(m => m.Id)</th>
                <th>@Html.DisplayNameFor(m => m.Type)</th>
                <th>@Html.DisplayNameFor(m => m.ApplyUser)</th>
                <th>@Html.DisplayNameFor(m => m.ApplyDate)</th>
                <th>@Html.DisplayNameFor(m => m.AuditDate)</th>
                <th>@Html.DisplayNameFor(m => m.AuditTimes)</th>
                <th>@Html.DisplayNameFor(m => m.CheckState)</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>@Html.DisplayFor(m => item.Id)</td>
                <td>@Html.DisplayFor(m => item.Type.Name)</td>
                <td>@Html.DisplayFor(m => item.ApplyUser.UserName)</td>
                <td>@Html.DisplayFor(m => item.ApplyDate)</td>
                <td>@Html.DisplayFor(m => item.AuditDate)</td>
                <td>@Html.DisplayFor(m => item.AuditTimes)</td>
                @if (item.CheckState == 1)
                {
                    <td style="color:blue">创建</td>
                    <td>
                        @Html.ActionLink("查看记录", "AuditClubDetail", new { id = item.Id }, new { @class = "layui-btn layui-btn-primary layui-btn-xs" })
                        @Html.ActionLink("开始审批", "AuditClubA", new { id = item.Id }, new { @class = "layui-btn layui-btn-xs" })
                    </td>
                }
                else if (item.CheckState == 2)
                {
                    <td style="color:green">通过</td>
                    <td>
                        @Html.ActionLink("查看记录", "AuditClubDetail", new { id = item.Id }, new { @class = "layui-btn layui-btn-primary layui-btn-xs" })
                    </td>
                }
                else if (item.CheckState == 3)
                {
                    <td style="color:red">拒绝</td>
                    <td>
                        @Html.ActionLink("查看记录", "AuditClubDetail", new { id = item.Id }, new { @class = "layui-btn layui-btn-primary layui-btn-xs" })
                    </td>
                }
            </tr>
            }
        </tbody>
    </table>
</div>
<script>
    $("#b1").addClass("layui-this");
    $("#b1").parents("li").addClass("layui-nav-itemed")
</script>

ClubApp/Views/BAdmin/AuditClubDetail.cshtml
@model IEnumerable<ClubApp.Models.AuditDetail>
@{
    ViewBag.Title = "审批明细";
}

<h2>@ViewBag.Msg</h2>
<fieldset class="layui-elem-field layui-field-title">
    <legend>审批记录以用户创建开始，审批结果不代表最终结果</legend>
</fieldset>
<ul class="layui-timeline">
    @foreach (var item in Model)
    {
        <li class="layui-timeline-item">
            <i class="layui-icon layui-timeline-axis">&#xe63f;</i>
            <div class="layui-timeline-content layui-text">
                <h3 class="layui-timeline-title">@item.AuditDate</h3>
                <p>
                    姓名：@(item.AuditUser==null?"未知":item.AuditUser.UserName)
                    <br>审批结果：
                    @if (item.CheckState == 1)
                    {
                        <span style="color:blue">创建</span>
                    }
                    else if (item.CheckState == 2)
                    {
                        <span style="color:green">通过</span>
                    }
                    else if (item.CheckState == 3)
                    {
                        <span style="color:red">拒绝</span>
                    }
                    else
                    {
                        <span>其他</span>
                    }
                    <br>备注：@item.AuditDesc
                </p>
            </div>
        </li>
    }
    <li class="layui-timeline-item">
        <i class="layui-icon layui-timeline-axis">&#xe63f;</i>
        <div class="layui-timeline-content layui-text">
            <h3 class="layui-timeline-title">申请编号：@(Model.FirstOrDefault()==null?"未创建":Model.FirstOrDefault().ApplyId.ToString())</h3>          
        </div>
    </li>
</ul>
<button type="button" onclick="JavaScript:history.go(-1)" class="layui-btn layui-btn-sm layui-btn-primary">
    <i class="layui-icon">&#xe65c;</i>返回
</button>
<script>
    $("#b1").addClass("layui-this");
</script>

ClubApp/Views/BAdmin/NoticesA.cshtml
@model ClubApp.Models.Notice
@{
    ViewBag.Title = "系统公告";
}
<button class="layui-btn layui-btn-sm layui-btn-primary" onclick="javascript:history.back(-1)"><i class="layui-icon layui-icon-return"></i>返回公告列表</button>
<hr />
<fieldset class="layui-elem-field">
    <legend>@Model.Title1</legend>
    <div class="layui-field-box">
        @Model.CreateDate.ToString("yyyy年MM月dd日：HH时mm分ss秒") <br /> @Model.Title2 
    </div>
</fieldset>
<div class="content">@(new HtmlString(Model.Content))</div>
<hr />