ClubApp/Models/ClubViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ClubApp.Models
{
    public class ClubListModel
    {
        [Display(Name ="编号")]
        public string cid { get; set; }
        [Display(Name="名称")]
        public string name { get; set; }
        [Display(Name="描述")]
        public string Desc { get; set; }
        [Display(Name ="创建时间")]
        public string CreateDate { get; set; }
        [Display(Name ="创建人")]
        public string CreateUser { get; set; }
        [Display(Name = "创建人")]
        public string CreateUserName { get; set; }
    }
    public class ClubViewModel
    {
        [Display(Name = "社团账号")]
        public string ClubId { get; set; }
        [Display(Name = "社团类型")]
        public string ClubType { get; set; }
        [Display(Name = "标签"), MaxLength(3)]
        public List<string> Labels { get; set; }
        [MaxLength(50), Display(Name = "社团名称")]
        public string Name { get; set; }
        [Display(Name = "头像"), MaxLength(500)]
        public string HeadImg { get; set; }
        [MaxLength(100), Display(Name = "签名")]
        public string ShortDesc { get; set; }
        [MaxLength(500), Display(Name = "描述")]
        public string Desc { get; set; }
        [Display(Name = "状态")]
        public string State { get; set; }
        [Display(Name = "创建日期")]
        public string CreateDate { get; set; }
        [Display(Name = "创建人")]
        public virtual UserNumber User { get; set; }
        [Display(Name="成员人数")]
        public int UserCount { get; set; }
        [Display(Name="最新活动")]
        public List<Activities> Activities { get; set; }
        [Display(Name="最新公告")]
        public List<AnnounceMent> announceMents { get; set; }
        [Display(Name="当前用户与社团关系")]
        public string status { get; set; }
    }
    public class UserClubModel
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        [Display(Name = "用户")]
        public string User { get; set; }
        public string ClubId { get; set; }
        [Display(Name = "社团")]
        public string Club { get; set; }
        [Display(Name = "职位/状态")]
        public string Status { get; set; }
        public int state { get; set; }
        [Display(Name = "社团状态")]
        public string CState { get; set; }
        [Display(Name = "创建时间")]
        public string CreateDate { get; set; }
        [Display(Name = "备注"), MaxLength(500)]
        public string Desc { get; set; }
        public int Enable { get; set; }
    }
    public class JoinClubSubModel
    {
        [Key, Display(Name = "社团账号"), MaxLength(10)]
        public string ClubId { get; set; }
        [Display(Name = "社团类型")]
        public string Type { get; set; }
        [MaxLength(50), Display(Name = "社团名称")]
        public string Name { get; set; }
        [Display(Name="社团人数")]
        public int UserCount { get; set; }
        [Display(Name = "头像"), MaxLength(500)]
        public string HeadImg { get; set; }
        [MaxLength(100), Display(Name = "签名")]
        public string ShortDesc { get; set; }
        [MaxLength(500), Display(Name = "社团描述")]
        public string Desc { get; set; }
        [Display(Name = "账号状态")]
        public string State { get; set; }
        [Display(Name = "创建日期")]
        [DataType(DataType.DateTime)]
        public string CreateDate { get; set; }
        [Display(Name = "创建人")]
        public string User { get; set; }
        [Display(Name = "申请理由"), MaxLength(500)]
        public string ApplyDesc { get; set; }
        [Display(Name = "附件")]
        public string ApplyFile { get; set; }
        [Display(Name = "是否可以申请加入")]
        public bool CanJoin { get; set; }
        [Display(Name = "上次处理日期")]
        public string AuditDate { get; set; }
        [Display(Name = "审批次数")]
        public int AuditTime { get; set; }
        [Display(Name = "审批编号")]
        public int AuditId { get; set; }
    }
    public class AuditJoinClubModel
    {
        [Display(Name ="社团")]
        public string ClubName { get; set; }
        public UserNumber UserInfo { get; set; }
        [Display(Name = "申请日期")]
        public string ApplyDate { get; set; }
        [Display(Name = "申请理由"), MaxLength(500)]
        public string ApplyDesc { get; set; }
        [Display(Name = "附件")]
        public string ApplyFile { get; set; }
        [Display(Name = "申请状态")]
        public string State { get; set; }
        [Display(Name = "上次处理日期")]
        public string AuditDate { get; set; }
        [Display(Name = "审批次数")]
        public int AuditTime { get; set; }
        [Display(Name = "审批编号")]
        public int AuditId { get; set; }
    }
}

ClubApp/Controllers/ClubsController.cs
using ClubApp.Models;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ClubApp.Controllers
{
    [Authorize]
    public class ClubsController : Controller
    {

        AppDbContext db = new AppDbContext();

        private AppUserManager _userManager;

        public ClubsController()
        {
        }

        public ClubsController(AppUserManager userManager)
        {
            UserManager = userManager;
        }

        public AppUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<AppUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        // GET: Clubs
        public ActionResult Index()
        {
            return View(db.ClubNumbers.Where(c => c.State == (int)EnumState.正常).ToList());
        }
        public ActionResult Club(string cid)
        {
            if (cid == null)
            {
                return RedirectToAction("MyClubs");
            }
            ClubNumber club = db.ClubNumbers.Find(cid);
            if (club == null)
            {
                return HttpNotFound("未发现社团" + cid);
            }
            List<UserClubs> ucs = db.UserClubs.Where(u => u.Club.ClubId == club.ClubId&&u.State>0&&u.State<5).ToList();
            List<Activities> activities = db.Activities.Where(a => a.Club.ClubId == club.ClubId).OrderBy(a=>a.Id).Take(5).ToList();
            List<AnnounceMent> announceMents = db.AnnounceMents.Where(a => a.Club.ClubId == club.ClubId && a.state == (int)EnumState.正常).OrderBy(a=>a.Id).Take(5).ToList();
            ClubViewModel model = new ClubViewModel()
            {
                ClubId = club.ClubId,
                ClubType = club.Type.Name,
                Labels = club.Label?.Split(',').ToList(),
                Name = club.Name,
                HeadImg = club.HeadImg?? "Content/images/head5.jpg",
                ShortDesc = club.ShortDesc,
                Desc = club.Desc,
                State = club.State == null ? "" : Enum.GetName(typeof(EnumState), club.State),
                CreateDate = club.CreateDate2 == null ? "未知" : club.CreateDate2.ToString(),
                User = club.User,
                UserCount = ucs.Count,
                Activities = activities,
                announceMents = announceMents,
                status="0"
            };
            if (User != null)
            {
                UserClubs uc = ucs.Where(u => u.User.UserId == User.Identity.Name).FirstOrDefault();
                if (uc!=null)
                {
                    model.status =Enum.GetName(typeof(UCStatus),uc.Status);
                }
            }

            return View(model);
        }
        public ActionResult ApplyClub(string Msg = "")
        {
            if (!string.IsNullOrEmpty(Msg))
            {
                ViewBag.Msg = Msg;
            }
            ApplyClubModel model = new ApplyClubModel();
            model.clubTypes = db.ClubTypes.ToList();
            return View(model);
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult ApplyClub(ApplyClubModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    UserNumber thisuser = db.UserNumbers.Find(User.Identity.Name);
                    ApplyType applyType = db.ApplyTypes.Find((int)SQType.注册社团);
                    if (applyType == null || applyType.Enable != 1)
                    {
                        throw new Exception("注册社团的申请通道暂未开通，请持续关注后续开通公告或联系管理员");
                    }
                    ClubNumber club = db.ClubNumbers.Where(c => c.User.UserId == User.Identity.Name).OrderByDescending(c => c.CreateDate).FirstOrDefault();
                    if (club != null && club.CreateDate != null)
                    {
                        if (DateTime.Now.Subtract((DateTime)club.CreateDate).Days < 1)
                        {
                            throw new Exception("每个用户每天只能申请一次社团创建！用户已于" + club.CreateDate.ToString() + "创建过申请！");
                        }
                    }
                    ClubNumber newclub = GetRandomClubNumber();
                    if (newclub == null || newclub.State != (int)EnumState.未使用)
                    {
                        throw new Exception("社团账号已达上限，暂无法新建社团。请联系管理员");
                    }

                    //ApplyAudit apply = new ApplyAudit()
                    //{
                    //    Type = applyType,
                    //    ApplicationDesc = model.ApplyDesc,
                    //    ApplicationFiled = model.ApplyFile,
                    //    ApplyDate=DateTime.Now,
                    //    ApplyUser=db.UserNumbers.Find(User.Identity.Name),
                    //    CheckState=(int)EnumAuditState.已创建,
                    //    AuditTimes=0                      
                    //};
                    newclub.Name = model.Name;
                    if (model.Label?.Length > 1)
                    {
                        newclub.Label = model.Label.Substring(1);
                    }
                    
                    newclub.Desc = model.Desc;
                    newclub.ShortDesc = model.ShortDesc;
                    newclub.CreateDate = DateTime.Now;
                    newclub.Type = db.ClubTypes.Find(model.Type);
                    newclub.User = thisuser;
                    newclub.State = (int)EnumState.待提交;

                    //添加关系
                    UserClubs uc = new UserClubs()
                    {
                        User = thisuser,
                        Club = newclub,
                        Status = (int)UCStatus.社长,
                        CreateDate = DateTime.Now,
                        State=(int)EnumState.正常
                    };
                    db.Entry(newclub).State = System.Data.Entity.EntityState.Modified;
                    db.UserClubs.Add(uc);
                    db.SaveChanges();
                    model = new ApplyClubModel();
                    model.ClubId = newclub.ClubId;
                    ViewBag.Res = "ApplyOK";
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }

            }
            model.clubTypes = db.ClubTypes.ToList();
            return View(model);
        }
        [HttpGet]
        public ActionResult JoinClub(string cid)
        {
            if (cid == null)
            {
                return RedirectToAction("Index");
            }
            ClubNumber club = db.ClubNumbers.Find(cid);
            if (club == null)
            {
                return HttpNotFound("未发现社团" + cid);
            }
            List<UserClubs> ucs = db.UserClubs.Where(u => u.Club.ClubId == club.ClubId && u.State > 0 && u.State < 5).ToList();
            JoinClubSubModel model = new JoinClubSubModel()
            {
                ClubId = club.ClubId,
                Type = club.Type.Name,
                Name = club.Name,
                HeadImg = club.HeadImg,
                ShortDesc = club.ShortDesc,
                Desc = club.Desc,
                State = Enum.GetName(typeof(EnumState), club.State),
                CreateDate = club.CreateDate == null ? "未知" : club.CreateDate.ToString(),
                User = club.User.UserName,
                UserCount=ucs.Count(),
                CanJoin= !ucs.Where(u => u.User.UserId == User.Identity.Name).Any()
            };
            return View(model);
        }
        [HttpPost]
        public ActionResult JoinClub([Bind(Include = "ClubId,ApplyDesc,ApplyFile")]JoinClubSubModel model)
        {
            try
            {
                ClubNumber club = db.ClubNumbers.Find(model.ClubId);
                UserNumber me = db.UserNumbers.Find(User.Identity.Name);
                if (string.IsNullOrWhiteSpace(model.ApplyFile))
                {
                    ModelState.AddModelError("", "申请任务未上传审批文件！");
                    return View(model);
                }
                if (db.UserClubs.Where(uc => uc.Club.ClubId == model.ClubId && uc.User.UserId == User.Identity.Name && uc.State > 0 && uc.State < 5).Any())
                {
                    ModelState.AddModelError("", "你已经是该社团成员或已申请加入该社团，不允许重复申请加入");
                    return View(model);
                }
                if (club.State != (int)EnumState.正常&& club.State != (int)EnumState.待提交)
                {
                    string state = club.State == null ? "未知" : Enum.GetName(typeof(EnumState), club.State);
                    ModelState.AddModelError("","社团"+club.ClubId+"状态为："+state+ " 不允许申请加入");
                    return View(model);
                }
                ApplyAudit apply = new ApplyAudit()
                {
                    Type = db.ApplyTypes.Find((int)SQType.加入社团),
                    ApplicationDesc = model.ApplyDesc,
                    ApplicationFiled = model.ApplyFile,
                    ApplyUser = me,
                    Club = club,
                    ApplyDate = DateTime.Now,
                    CheckState = (int)EnumAuditState.创建,
                    AuditTimes = 0
                };
                db.ApplyAudits.Add(apply);
                db.SaveChanges();

                AuditDetail audit = new AuditDetail()
                {
                    ApplyId = apply.Id,
                    CheckState = (int)EnumAuditState.创建,
                    AuditUser = me,
                    AuditDate = DateTime.Now

ClubApp/Views/Clubs/ApplyClub.cshtml
@model ClubApp.Models.ApplyClubModel
@{
    ViewBag.Title = "创建社团";
}
<style>
    .layui-form-danger {
        border-color: red;
    }
</style>
@if ((ViewBag.Res ?? "") == "ApplyOK")
{
    <fieldset class="layui-elem-field">
        <legend>申请结果</legend>
        <div class="layui-field-box text-danger">
            社团申请已成功创建，已为你锁定[@Model.ClubId]的账号，请在24小时内通过菜单：[社团-@Html.ActionLink("管理我的社团", "MyClubs", "Clubs")] 上传申请材料进行提交本次申请，逾期分配的账号可能会被收回。
        </div>
    </fieldset>
}
@using (Html.BeginForm("ApplyClub", "Clubs", FormMethod.Post, new { @class = "layui-form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
    <div class="layui-form-item">
        @Html.LabelFor(m => m.clubTypes, new { @class = "layui-form-label" })
        <div class="layui-input-inline">
            <select name="Type" lay-verify="required">
                <option value="">请选择申请社团类型</option>
                @foreach (var item in Model.clubTypes)
                {
                    if (item.Enable == 1)
                    {
                        <option value="@item.Id">@item.Name</option>
                    }
                    else
                    {
                        <option value="@item.Id" disabled>@item.Name | 未激活</option>
                    }
                }
            </select>
        </div>
        <div class="layui-form-mid layui-word-aux">
            未找到合适选项或者选项不可用请联系管理员。
        </div>
    </div>
    <div class="layui-form-item">
        @Html.LabelFor(m => m.Label, new { @class = "layui-form-label" })
        <div class="layui-input-block">
            <input type="checkbox" name="like" title="文学">
            <input type="checkbox" name="like" title="编程">
            <input type="checkbox" name="like" title="游戏">
            <input type="checkbox" name="like" title="体育">
            <input type="checkbox" name="like" title="社交">
            <input type="checkbox" name="like" title="音乐">
            <input type="checkbox" name="like" title="科学">
            <input type="checkbox" name="like" title="商务">
            <input type="checkbox" name="like" title="男女">
            <input type="button" class="layui-btn layui-btn-sm layui-btn-primary" onclick="addlabel()" value="更多" />
            @Html.TextBoxFor(m => m.Label, new { @class = "layui-input layui-hide" })
        </div>
    </div>
    <div class="layui-form-item">
        @Html.LabelFor(m => m.Name, new { @class = "layui-form-label" })
        <div class="layui-input-block">
            @Html.TextBoxFor(m => m.Name, new { @class = "layui-input", autocomplete = "off" })
        </div>
    </div>

    <div class="layui-form-item">
        @Html.LabelFor(m => m.ShortDesc, new { @class = "layui-form-label" })
        <div class="layui-input-block">
            @Html.TextBoxFor(m => m.ShortDesc, new { @class = "layui-input", autocomplete = "off" })
        </div>
    </div>
    <div class="layui-form-item">
        @Html.LabelFor(m => m.Desc, new { @class = "layui-form-label" })
        <div class="layui-input-block">
            <textarea name="Desc" required lay-verify="required|maxlength" placeholder="对该社团做个简单的介绍会更容易吸引同学参加哟（最大500字符）" class="layui-textarea">@(Model.ApplyDesc??"")</textarea>
        </div>
    </div>
    <div class="layui-form-item">
        <div class="layui-input-block">
            <button class="layui-btn" lay-submit lay-filter="demo2">确认提交</button>
            <button type="reset" class="layui-btn layui-btn-primary">重置</button>
        </div>
    </div>

}

<script>
    //Demo
    layui.use('form', function () {
        var form = layui.form;
        form.verify({
            maxlength: function (value, item) {
                if (value.length > 500) {
                    return '超过最大长度[500]个字符！'
                }
            }
        });
        //监听提交
        form.on('submit(demo2)', function (data) {
            if ($('input[name="like"]:checked').length > 3) {
                layer.msg("社团标签最多可选择3个");
                return false;
            }
            var label = "";
            $('input[name="like"]:checked').each(function () {
                label = label + "," + this.title;
            });
            $("#Label").val(label);
        });
    });
    function addlabel() {
        layer.msg('暂不支持自定义标签');
    }
    $("#c3").addClass("layui-this");
    $("#c3").parents("li").addClass("layui-nav-itemed")
</script>

ClubApp/Views/Clubs/ApplyClubInfo.cshtml
@model ClubApp.Models.ClubNumber
@{
    ViewBag.Title = "社团信息";
}

<h2>社团信息</h2>
@using (Html.BeginForm("ApplyClubInfo", "Clubs", FormMethod.Post, new { @class = "layui-form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="layui-form-item">
        @Html.LabelFor(m => m.Type, new { @class = "layui-form-label" })
        <div class="layui-input-inline">
            <label class="layui-input">@Model.Type.Name</label>
        </div>
        <div class="layui-form-mid layui-word-aux">
            社团类型应与申请时一致，不允许更改。
        </div>
    </div>
    <div class="layui-form-item">
        @Html.LabelFor(m => m.Name, new { @class = "layui-form-label" })
        <div class="layui-input-block">
            @Html.TextBoxFor(m => m.Name, new { @class = "layui-input" })
        </div>
    </div>
    <div class="layui-form-item">
        @Html.LabelFor(m => m.HeadImg, new { @class = "layui-form-label" })
        <div class="layui-input-inline">
            <div class="layui-upload-drag" id="uploadDemo">
                <i class="layui-icon"></i>
                <p>点击上传，或将文件拖拽到此处</p>
            </div>
        </div>
        <div class="layui-input-inline">
            <div class="layui-upload-drag" id="uploadDemo">
                <i class="layui-icon"></i>
                <p>点击上传，或将文件拖拽到此处</p>
            </div>
        </div>
    </div>
    <div class="layui-form-item">
        @Html.LabelFor(m => m.ShortDesc, new { @class = "layui-form-label" })
        <div class="layui-input-block">
            @Html.TextBoxFor(m => m.ShortDesc, new { @class = "layui-input" })
        </div>
    </div>
    <div class="layui-form-item">
        @Html.LabelFor(m => m.Desc, new { @class = "layui-form-label" })
        <div class="layui-input-block">
            @Html.TextAreaFor(m => m.Desc, new { @class = "layui-input", placeholder = "对该社团做个简单的介绍会更容易吸引同学参加哟（最大500字符）" })
        </div>
    </div>
    <div class="layui-form-item">
        <div class="layui-input-block">
            <input type="submit" class="layui-btn" lay-submit value="确认提交" />
            <button type="reset" class="layui-btn layui-btn-primary">重置</button>
        </div>
    </div>

}
<script>
        //Demo
        layui.use(['form', 'upload'], function () {
            var form = layui.form
                , upload = layui.upload;
            //监听提交
            form.on('submit(formDemo)', function (data) {
                layer.msg(JSON.stringify(data.field));
                return false;
            });
            form.verify({
                maxlength: function (value, item) {
                    if (value.length > 500) {
                        return '超过最大长度[500]个字符！'
                    }
                }
                , required: function (value) {
                    if (value != 1) {
                        return '未上传审批文件的申请不允许提交'
                    }
                }
            })

            //上传
            upload.render({
                elem: '#uploadDemo'
                , url: '/#' //上传接口
                , accept: 'file'
                , exts: 'zip|rar|7z'
                , auto:false
                , size: 2048
                , data: {
                    id: function () {
                        return $("#Id").val();
                    }
                }
                , done: function (res) {
                    if (res.code == 0) {
                        window.Location.reload();
                    }
                    else {
                        alert(res.msg);
                    }
                }
                , error: function (index, upload) {
                    alert("文件上传失败（非服务器异常）")
                }
            });
        });
</script>

ClubApp/Views/Clubs/JoinClub.cshtml
@model ClubApp.Models.JoinClubSubModel
@{
    ViewBag.Title = "提交申请";
}
<style>
    .form-diy-r {
        padding: 9px 15px;
        display: block;
    }
</style>
<fieldset class="layui-elem-field layui-field-title">
    <legend>申请加入 @Model.Name</legend>
</fieldset>
@using (Html.BeginForm("JoinClub", "Clubs", FormMethod.Post, new { @class = "layui-form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
    <div class="layui-form-item">
        <div class="layui-inline">
            @Html.LabelFor(m => m.ClubId, new { @class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.TextBoxFor(m => m.ClubId, new { @class = "layui-input", @readonly = "true" })
            </div>
        </div>
        <div class="layui-inline">
            @Html.LabelFor(m => m.UserCount, new { @class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.TextBoxFor(m => m.UserCount, new { @class = "layui-input", @readonly = "true" })
            </div>
        </div>
        <div class="layui-inline">
            @Html.LabelFor(m => m.User, new { @class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.TextBoxFor(m => m.User, new { @class = "layui-input", @readonly = "true" })
            </div>
        </div>
    </div>
    <div class="layui-form-item">
        <div class="layui-inline">
            @Html.LabelFor(m => m.Type, new { @class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.TextBoxFor(m => m.Type, new { @class = "layui-input", @readonly = "true" })
            </div>
        </div>
        <div class="layui-inline">
            @Html.LabelFor(m => m.State, new { @class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.TextBoxFor(m => m.State, new { @class = "layui-input", @readonly = "true" })
            </div>
        </div>
        <div class="layui-inline">
            @Html.LabelFor(m => m.CreateDate, new { @class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.TextBoxFor(m => m.CreateDate, new { @class = "layui-input", @readonly = "true" })
            </div>
        </div>
    </div>
    <div class="layui-form-item">
        @Html.LabelFor(m => m.ShortDesc, new { @class = "layui-form-label" })
        <div class="layui-input-block">
            @Html.TextBoxFor(m => m.ShortDesc, new { @class = "layui-input", @readonly = "true" })
        </div>
    </div>
    <div class="layui-form-item">
        <div class="layui-inline">
            @Html.LabelFor(m => m.HeadImg, new { @class = "layui-form-label" })
            <div class="layui-input-inline">
                <img src="~/@Model.HeadImg" id="clubimg" style="max-height:150px;max-width:150px" />
            </div>
        </div>
    </div>
    <div class="layui-form-item">
        @Html.LabelFor(m => m.Desc, new { @class = "layui-form-label" })
        <div class="layui-input-block">
            <textarea name="Desc" required lay-verify="required|maxlength" readonly placeholder="对该社团做个简单的介绍会更容易吸引同学参加哟（最大500字符）" class="layui-textarea">@(Model.Desc??"")</textarea>
        </div>
    </div>
    if (Model.CanJoin)
    {
        <div class="layui-form-item">
            <label class="layui-form-label">申请理由<span style="color:red">*</span></label>
            <div class="layui-input-block">
                <textarea name="ApplyDesc" required lay-verify="required|maxlength" placeholder="请简述你申请加入本社团的原因及意义（最大500字符）" class="layui-textarea"></textarea>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">附件<span style="color:red">*</span></label>
            <div class="layui-input-inline">
                <div class="layui-upload-drag" id="uploadDemo">
                    <i class="layui-icon"></i>
                    <p>点击上传，或将文件拖拽到此处</p>
                </div>
            </div>
            <div class="layui-form-mid layui-word-aux">
                请将文档图片等材料打包压缩后上传（.zip/.rar/最大2M）<br />
                申请材料清单(<span class="text-danger">以下内容必须包括，否则申请不予通过</span>。可附上其他有效材料)：<br />
                <ul>
                    <li>《个人简介.doc》对自己进行简单的介绍</li>
                    <li>个人证件照一份</li>
                </ul>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">已上传附件</label>
            <div class="layui-input-block">
                <a href="#" id="file_link" class="form-diy-r">无</a>
                <input type="text" id="file_upver" lay-verify="uprequired" name="ApplyFile" class="layui-input layui-hide" />
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-input-block">
                <input type="submit" id="subbtn" class="layui-btn" lay-submit value="确认提交" />
                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
            </div>
        </div>
    }
    else
    {
        <div class="layui-form-item">
            <label class="layui-form-label">申请材料</label>
            <div class="layui-input-block">
                <blockquote class="layui-elem-quote layui-quote-nm">
                    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 30px;">
                        <legend>密封线内 - 不准答题</legend>
                    </fieldset>
                </blockquote>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-input-block">
                @Html.ActionLink("返回我的社团", "MyClubs", null, new { @class = "layui-btn" })
                <label class="form-diy-r layui-bg-red">你已经是该社团成员或已申请加入该社团，不允许重复申请加入</label>
            </div>
        </div>
    }

}
<script>
    //Demo
    layui.use(['form', 'upload'], function () {
        var form = layui.form
            , upload = layui.upload;
        //监听提交
        form.on('submit(formDemo)', function (data) {
            layer.msg(JSON.stringify(data.field));
            return false;
        });
        form.verify({
            maxlength: function (value, item) {
                if (value.length > 500) {
                    return '超过最大长度[500]个字符！'
                }
            }
            , uprequired: function (value) {
                if (value.length < 1) {
                    return '未上传审批文件的申请不允许提交'
                }
            }
        })
        //上传
        upload.render({
            elem: '#uploadDemo'
            , url: '/Upload/JoinClubFile' //上传接口
            , accept: 'file'
            , exts: 'zip|rar|7z'
            , size: 2048
            , data: {
                cid: function () {
                    return $("#ClubId").val();
                }
            }
            , before: function (obj) { //obj参数包含的信息，跟 choose回调完全一致，可参见上文。
                layer.load(); //上传loading
            }
            , done: function (res) {
                layer.closeAll('loading'); //关闭loading
                if (res.code == 0) {
                    $("#file_link").attr("href", "../../" + res.src);
                    $("#file_link").html(res.name);
                    $("#file_upver").val(res.src)
                }
                else {
                    alert(res.msg);
                }
            }
            , error: function (index, upload) {
                alert("文件上传失败（非服务器异常）")
            }
        });
    });
    $("#c2").addClass("layui-this");
    $("#c2").parents("li").addClass("layui-nav-itemed")
</script>